// ============================================================================
// scalings.xyz — Export Service (Target Config Generation)
// ============================================================================

import {
  ExportService,
  SimulationConfig,
  TargetConfig,
  TargetFormat,
} from '../interfaces/types.js';

export class LocalExportService implements ExportService {
  generate(config: SimulationConfig): TargetConfig {
    switch (config.platform) {
      case 'kubernetes-hpa':
        return this.generateKubernetes(config);
      case 'aws-asg':
        return this.generateAWS(config);
      case 'gcp-mig':
        return this.generateGCP(config);
      case 'custom':
        return this.generateCustom(config);
      default:
        return this.generateKubernetes(config);
    }
  }

  private generateKubernetes(config: SimulationConfig): TargetConfig {
    const content = `apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  labels:
    app: my-app
    generated-by: scalings.xyz
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: ${config.scaling.min_replicas}
  maxReplicas: ${config.scaling.max_replicas}
  metrics:
  - type: Resource
    resource:
      name: cpu  # placeholder - replace with your actual bottleneck metric
      target:
        type: Utilization
        averageUtilization: ${config.scaling.scale_up_threshold}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: ${config.advanced.cooldown_scale_up}
      policies:
      - type: Pods
        value: ${config.scaling.scale_up_step}
        periodSeconds: ${config.advanced.cooldown_scale_up}
    scaleDown:
      stabilizationWindowSeconds: ${config.advanced.cooldown_scale_down}
      policies:
      - type: Pods
        value: ${config.scaling.scale_down_step}
        periodSeconds: ${config.advanced.cooldown_scale_down}`;

    return {
      platform: 'kubernetes-hpa',
      format: 'kubernetes-yaml',
      content,
    };
  }

  private generateAWS(config: SimulationConfig): TargetConfig {
    const content = `# AWS Auto Scaling Group - CloudFormation snippet
# Generated by scalings.xyz

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '${config.scaling.min_replicas}'
      MaxSize: '${config.scaling.max_replicas}'
      DesiredCapacity: '${config.scaling.min_replicas}'
      HealthCheckGracePeriod: ${config.scaling.startup_time}
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: generated-by
          Value: scalings.xyz
          PropagateAtLaunch: true

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalLowerBound: 0
          ScalingAdjustment: ${config.scaling.scale_up_step}
      Cooldown: ${config.advanced.cooldown_scale_up}

  ScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalUpperBound: 0
          ScalingAdjustment: -${config.scaling.scale_down_step}
      Cooldown: ${config.advanced.cooldown_scale_down}

  HighUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale up when utilization > ${config.scaling.scale_up_threshold}%
      MetricName: CPUUtilization  # Replace with your bottleneck metric
      Namespace: AWS/EC2
      Statistic: Average
      Period: ${config.advanced.metric_observation_delay}
      EvaluationPeriods: 1
      Threshold: ${config.scaling.scale_up_threshold}
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ScaleUpPolicy

  LowUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale down when utilization < ${config.scaling.scale_down_threshold}%
      MetricName: CPUUtilization  # Replace with your bottleneck metric
      Namespace: AWS/EC2
      Statistic: Average
      Period: ${config.advanced.metric_observation_delay}
      EvaluationPeriods: 1
      Threshold: ${config.scaling.scale_down_threshold}
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref ScaleDownPolicy`;

    return {
      platform: 'aws-asg',
      format: 'cloudformation',
      content,
    };
  }

  private generateGCP(config: SimulationConfig): TargetConfig {
    const content = `# GCP Managed Instance Group - Terraform configuration
# Generated by scalings.xyz

resource "google_compute_autoscaler" "app_autoscaler" {
  name   = "my-app-autoscaler"
  zone   = "us-central1-a"  # Update with your zone
  target = google_compute_instance_group_manager.app_mig.id

  autoscaling_policy {
    min_replicas    = ${config.scaling.min_replicas}
    max_replicas    = ${config.scaling.max_replicas}
    cooldown_period = ${config.advanced.cooldown_scale_up}

    cpu_utilization {
      target = ${(config.scaling.scale_up_threshold / 100).toFixed(2)}  # Replace with your bottleneck metric
    }

    scale_in_control {
      max_scaled_in_replicas {
        fixed = ${config.scaling.scale_down_step}
      }
      time_window_sec = ${config.advanced.cooldown_scale_down}
    }
  }
}

resource "google_compute_instance_group_manager" "app_mig" {
  name               = "my-app-mig"
  zone               = "us-central1-a"  # Update with your zone
  base_instance_name = "my-app"

  version {
    instance_template = google_compute_instance_template.app_template.id
  }

  named_port {
    name = "http"
    port = 8080
  }

  auto_healing_policies {
    health_check      = google_compute_health_check.app_health.id
    initial_delay_sec = ${config.scaling.startup_time}
  }
}

resource "google_compute_health_check" "app_health" {
  name                = "my-app-health-check"
  check_interval_sec  = ${Math.max(5, Math.floor(config.advanced.metric_observation_delay / 3))}
  timeout_sec         = 5
  healthy_threshold   = 2
  unhealthy_threshold = 3

  http_health_check {
    port = 8080
    request_path = "/health"
  }
}`;

    return {
      platform: 'gcp-mig',
      format: 'terraform',
      content,
    };
  }

  private generateCustom(config: SimulationConfig): TargetConfig {
    const content = `# Custom / Generic Autoscaling Configuration
# Generated by scalings.xyz
# Adapt this to your specific autoscaling platform.

autoscaling:
  min_instances: ${config.scaling.min_replicas}
  max_instances: ${config.scaling.max_replicas}

  scale_up:
    threshold: ${config.scaling.scale_up_threshold}%  # Utilization threshold
    step_size: ${config.scaling.scale_up_step}
    cooldown: ${config.advanced.cooldown_scale_up}s

  scale_down:
    threshold: ${config.scaling.scale_down_threshold}%  # Utilization threshold
    step_size: ${config.scaling.scale_down_step}
    cooldown: ${config.advanced.cooldown_scale_down}s

  instance:
    startup_time: ${config.scaling.startup_time}s
    capacity: ${config.scaling.capacity_per_replica} rps
    graceful_shutdown: ${config.advanced.graceful_shutdown_time}s

  monitoring:
    metric_delay: ${config.advanced.metric_observation_delay}s
    observation_window: ${config.advanced.cooldown_scale_up}s

  infrastructure:
    node_provisioning_time: ${config.advanced.node_provisioning_time}s
    pods_per_node: ${config.advanced.cluster_node_capacity}

  cost:
    per_instance_hour: $${config.advanced.cost_per_replica_hour}`;

    return {
      platform: 'custom',
      format: 'terraform',
      content,
    };
  }
}
