// ============================================================================
// scalings.xyz — Gatling Load Test Exporter
// ============================================================================

import {
  LoadTestExporter,
  LoadTestRequestConfig,
  LoadTestValidationResult,
  SimulationConfig,
  SimulationResult,
  SteadyParams,
  GradualParams,
  SpikeParams,
  WaveParams,
  StepParams,
  CustomParams,
  GrafanaParams,
} from '../../interfaces/types.js';

export class GatlingExporter implements LoadTestExporter {
  readonly id = 'gatling' as const;
  readonly name = 'Gatling';
  readonly extension = 'java';

  generate(config: SimulationConfig, targetUrl: string, avgResponseTime: number, request: LoadTestRequestConfig, results?: SimulationResult): string {
    const duration = config.simulation.duration;
    const traffic = config.producer.traffic;
    const configJson = JSON.stringify(config);
    const shareUrl = `https://scalings.xyz/#config=${btoa(unescape(encodeURIComponent(configJson)))}`;
    const method = request.method.toLowerCase();
    const hasBody = (method === 'post' || method === 'put' || method === 'patch') && request.body.trim() !== '';

    const lines: string[] = [];
    lines.push(`// Generated by scalings.xyz — Autoscaling Simulator`);
    lines.push(`// Source config: ${config.name}`);
    lines.push(`// Simulation URL: ${shareUrl}`);
    lines.push(``);
    lines.push(`import io.gatling.javaapi.core.*;`);
    lines.push(`import io.gatling.javaapi.http.*;`);
    lines.push(``);
    lines.push(`import static io.gatling.javaapi.core.CoreDsl.*;`);
    lines.push(`import static io.gatling.javaapi.http.HttpDsl.*;`);
    lines.push(``);
    lines.push(`import java.time.Duration;`);
    lines.push(``);
    lines.push(`public class ScalingsSimulation extends Simulation {`);
    lines.push(``);
    lines.push(`    // Tunable: adjust to match your service's baseline response time`);
    lines.push(`    private static final int AVG_RESPONSE_TIME_MS = ${Math.round(avgResponseTime)};`);
    lines.push(``);
    lines.push(`    HttpProtocolBuilder httpProtocol = http`);
    lines.push(`        .baseUrl("${targetUrl}")`);
    lines.push(`        .acceptHeader("application/json")`);

    // Add custom headers from request config
    const headerEntries = Object.entries(request.headers);
    for (const [name, value] of headerEntries) {
      const resolvedValue = this.replaceTemplateVars(value);
      lines.push(`        .header("${name}", "${resolvedValue}")`);
    }

    lines.push(`        .userAgentHeader("scalings.xyz/loadtest");`);
    lines.push(``);

    // Build the scenario with correct HTTP method and optional body
    lines.push(`    ScenarioBuilder scenario = scenario("Scalings Load Test")`);
    lines.push(`        .exec(`);
    lines.push(`            http("request")`);
    lines.push(`                .${method}("/")`);

    if (hasBody) {
      const resolvedBody = this.replaceTemplateVars(request.body.trim());
      lines.push(`                .body(StringBody("${this.escapeJavaString(resolvedBody)}"))`);
    }

    lines.push(`                .check(status().is(200))`);
    lines.push(`        )`);
    lines.push(`        .pause(Duration.ofMillis(AVG_RESPONSE_TIME_MS));`);
    lines.push(``);

    const injection = this.buildInjection(traffic.pattern, traffic.params, duration, avgResponseTime);
    const assertions = this.buildAssertions(results);

    lines.push(`    {`);
    lines.push(`        setUp(`);
    lines.push(`            scenario.injectOpen(`);
    for (let i = 0; i < injection.length; i++) {
      const comma = i < injection.length - 1 ? ',' : '';
      lines.push(`                ${injection[i]}${comma}`);
    }
    lines.push(`            )`);
    lines.push(`        ).protocols(httpProtocol)`);
    if (assertions.length > 0) {
      lines.push(`        .assertions(`);
      for (let i = 0; i < assertions.length; i++) {
        const comma = i < assertions.length - 1 ? ',' : '';
        lines.push(`            ${assertions[i]}${comma}`);
      }
      lines.push(`        )`);
    }
    lines.push(`        ;`);
    lines.push(`    }`);
    lines.push(`}`);

    return lines.join('\n');
  }

  validate(config: SimulationConfig): LoadTestValidationResult {
    const warnings: string[] = [];
    const errors: string[] = [];

    const duration = config.simulation.duration;
    if (duration < 10) {
      warnings.push('Very short duration (< 10s) — Gatling may not produce meaningful results.');
    }

    const peakRps = this.estimatePeakRps(config);
    if (peakRps > 100000) {
      warnings.push(`Peak RPS of ~${Math.round(peakRps).toLocaleString()} will require many concurrent users. Consider Gatling Enterprise for distributed execution.`);
    }

    if (config.producer.traffic.pattern === 'wave') {
      warnings.push('Wave patterns are approximated as stepped ramps in Gatling.');
    }

    return { valid: errors.length === 0, warnings, errors };
  }

  private replaceTemplateVars(input: string): string {
    return input
      .replace(/\$randInt/g, '#{randomInt(0, 10000)}')
      .replace(/\$randString/g, '#{randomAlphanumeric(10)}')
      .replace(/\$uuid/g, '" + java.util.UUID.randomUUID().toString() + "')
      .replace(/\$timestamp/g, '" + System.currentTimeMillis() + "')
      .replace(/\$randFloat/g, '" + Math.random() + "')
      .replace(/\$randomEmail/g, '" + "user" + new java.util.Random().nextInt(100000) + "@loadtest.scalings.xyz" + "');
  }

  private escapeJavaString(input: string): string {
    return input.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  }

  private buildInjection(pattern: string, params: unknown, duration: number, avgResponseTime: number): string[] {
    switch (pattern) {
      case 'steady': return this.steadyInjection(params as SteadyParams, duration);
      case 'gradual': return this.gradualInjection(params as GradualParams, duration);
      case 'spike': return this.spikeInjection(params as SpikeParams, duration);
      case 'wave': return this.waveInjection(params as WaveParams, duration);
      case 'step': return this.stepInjection(params as StepParams);
      case 'custom':
      case 'grafana': return this.customInjection(params as CustomParams, duration);
      default: return this.steadyInjection({ rps: 100 }, duration);
    }
  }

  private steadyInjection(params: SteadyParams, duration: number): string[] {
    return [
      `constantUsersPerSec(${params.rps}).during(Duration.ofSeconds(${duration}))`,
    ];
  }

  private gradualInjection(params: GradualParams, duration: number): string[] {
    return [
      `rampUsersPerSec(${params.start_rps}).to(${params.end_rps}).during(Duration.ofSeconds(${duration}))`,
    ];
  }

  private spikeInjection(params: SpikeParams, duration: number): string[] {
    const steps: string[] = [];
    const spikeEnd = params.spike_start + params.spike_duration;

    if (params.spike_start > 0) {
      steps.push(`constantUsersPerSec(${params.base_rps}).during(Duration.ofSeconds(${params.spike_start}))`);
    }
    steps.push(`rampUsersPerSec(${params.base_rps}).to(${params.spike_rps}).during(Duration.ofSeconds(${Math.max(1, Math.min(5, Math.floor(params.spike_duration * 0.1)))}))`);
    steps.push(`constantUsersPerSec(${params.spike_rps}).during(Duration.ofSeconds(${Math.max(1, params.spike_duration - Math.max(1, Math.min(5, Math.floor(params.spike_duration * 0.1))))}))`);

    if (spikeEnd < duration) {
      steps.push(`rampUsersPerSec(${params.spike_rps}).to(${params.base_rps}).during(Duration.ofSeconds(${Math.min(5, duration - spikeEnd)}))`);
      const remaining = duration - spikeEnd - Math.min(5, duration - spikeEnd);
      if (remaining > 0) {
        steps.push(`constantUsersPerSec(${params.base_rps}).during(Duration.ofSeconds(${remaining}))`);
      }
    }

    return steps;
  }

  private waveInjection(params: WaveParams, duration: number): string[] {
    // Approximate sine wave with stepped ramps
    const stepsPerPeriod = 8;
    const periods = Math.max(1, Math.floor(duration / params.period));
    const totalSteps = periods * stepsPerPeriod;
    const stepDuration = Math.max(1, Math.floor(duration / totalSteps));
    const steps: string[] = [];

    let prevRps = params.base_rps;
    for (let i = 0; i < totalSteps; i++) {
      const angle = (2 * Math.PI * i) / stepsPerPeriod;
      const rps = Math.max(1, Math.round(params.base_rps + params.amplitude * Math.sin(angle)));
      steps.push(`rampUsersPerSec(${prevRps}).to(${rps}).during(Duration.ofSeconds(${stepDuration}))`);
      prevRps = rps;
    }

    return steps;
  }

  private stepInjection(params: StepParams): string[] {
    const steps: string[] = [];
    for (const step of params.steps) {
      steps.push(`constantUsersPerSec(${step.rps}).during(Duration.ofSeconds(${step.duration}))`);
    }
    return steps;
  }

  private customInjection(params: CustomParams, duration: number): string[] {
    const series = params.series;
    if (!series || series.length === 0) return this.steadyInjection({ rps: 100 }, duration);
    if (series.length === 1) return this.steadyInjection({ rps: series[0].rps }, duration);

    const steps: string[] = [];
    for (let i = 1; i < series.length; i++) {
      const segDuration = Math.max(1, Math.round(series[i].t - series[i - 1].t));
      const fromRps = Math.max(1, Math.round(series[i - 1].rps));
      const toRps = Math.max(1, Math.round(series[i].rps));
      steps.push(`rampUsersPerSec(${fromRps}).to(${toRps}).during(Duration.ofSeconds(${segDuration}))`);
    }

    // Hold last value until end
    const lastT = series[series.length - 1].t;
    if (lastT < duration) {
      const lastRps = Math.max(1, Math.round(series[series.length - 1].rps));
      steps.push(`constantUsersPerSec(${lastRps}).during(Duration.ofSeconds(${Math.round(duration - lastT)}))`);
    }

    return steps;
  }

  private buildAssertions(results?: SimulationResult): string[] {
    if (!results) return [];

    const assertions: string[] = [];
    const dropRate = results.summary.drop_rate_percent;

    if (dropRate > 0) {
      const failThreshold = Math.max(1, Math.ceil(dropRate * 1.5));
      assertions.push(`global().failedRequests().percent().lt(${failThreshold}.0)`);
    } else {
      assertions.push(`global().failedRequests().percent().lt(1.0)`);
    }

    if (results.summary.peak_queue_wait_time_ms > 0) {
      const p95Ms = Math.ceil(results.summary.peak_queue_wait_time_ms * 0.95);
      assertions.push(`global().responseTime().percentile3().lt(${p95Ms})`);
    }

    return assertions;
  }

  private estimatePeakRps(config: SimulationConfig): number {
    const p = config.producer.traffic.params;
    switch (config.producer.traffic.pattern) {
      case 'steady': return (p as SteadyParams).rps;
      case 'gradual': return Math.max((p as GradualParams).start_rps, (p as GradualParams).end_rps);
      case 'spike': return (p as SpikeParams).spike_rps;
      case 'wave': return (p as WaveParams).base_rps + (p as WaveParams).amplitude;
      case 'step': return Math.max(...(p as StepParams).steps.map(s => s.rps), 0);
      case 'custom':
      case 'grafana': return Math.max(...((p as CustomParams).series || []).map(s => s.rps), 0);
      default: return 0;
    }
  }
}
