// ============================================================================
// scalings.xyz — JMeter Load Test Exporter
// ============================================================================

import {
  LoadTestExporter,
  LoadTestRequestConfig,
  LoadTestValidationResult,
  SimulationConfig,
  SimulationResult,
  SteadyParams,
  GradualParams,
  SpikeParams,
  WaveParams,
  StepParams,
  CustomParams,
  GrafanaParams,
} from '../../interfaces/types.js';

export class JMeterExporter implements LoadTestExporter {
  readonly id = 'jmeter' as const;
  readonly name = 'JMeter';
  readonly extension = 'jmx';

  generate(config: SimulationConfig, targetUrl: string, avgResponseTime: number, request: LoadTestRequestConfig, results?: SimulationResult): string {
    const avgResponseSec = avgResponseTime / 1000;
    const duration = config.simulation.duration;
    const traffic = config.producer.traffic;
    const configJson = JSON.stringify(config);
    const shareUrl = `https://scalings.xyz/#config=${btoa(unescape(encodeURIComponent(configJson)))}`;

    let parsedUrl: { protocol: string; host: string; port: string; path: string };
    try {
      const u = new URL(targetUrl);
      parsedUrl = {
        protocol: u.protocol.replace(':', ''),
        host: u.hostname,
        port: u.port || (u.protocol === 'https:' ? '443' : '80'),
        path: u.pathname,
      };
    } catch {
      parsedUrl = { protocol: 'https', host: 'api.example.com', port: '443', path: '/' };
    }

    const threadGroups = this.buildThreadGroups(traffic.pattern, traffic.params, duration, avgResponseSec, request);
    const assertions = this.buildAssertions(results);

    return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scalings.xyz — Autoscaling Simulator
  Source config: ${this.escapeXml(config.name)}
  Simulation URL: ${this.escapeXml(shareUrl)}
-->
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Scalings Load Test">
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments">
        <collectionProp name="Arguments.arguments">
          <elementProp name="TARGET_HOST" elementType="Argument">
            <stringProp name="Argument.name">TARGET_HOST</stringProp>
            <stringProp name="Argument.value">${parsedUrl.host}</stringProp>
          </elementProp>
          <elementProp name="TARGET_PORT" elementType="Argument">
            <stringProp name="Argument.name">TARGET_PORT</stringProp>
            <stringProp name="Argument.value">${parsedUrl.port}</stringProp>
          </elementProp>
          <elementProp name="TARGET_PATH" elementType="Argument">
            <stringProp name="Argument.name">TARGET_PATH</stringProp>
            <stringProp name="Argument.value">${this.escapeXml(parsedUrl.path)}</stringProp>
          </elementProp>
          <elementProp name="TARGET_PROTOCOL" elementType="Argument">
            <stringProp name="Argument.name">TARGET_PROTOCOL</stringProp>
            <stringProp name="Argument.value">${parsedUrl.protocol}</stringProp>
          </elementProp>
        </collectionProp>
      </elementProp>
    </TestPlan>
    <hashTree>
${threadGroups}
      <!-- HTTP Request Defaults -->
      <ConfigTestElement guiclass="HttpDefaultsGui" testclass="ConfigTestElement" testname="HTTP Request Defaults">
        <stringProp name="HTTPSampler.protocol">\${TARGET_PROTOCOL}</stringProp>
        <stringProp name="HTTPSampler.domain">\${TARGET_HOST}</stringProp>
        <stringProp name="HTTPSampler.port">\${TARGET_PORT}</stringProp>
        <!-- Add custom headers or authentication here using an HTTP Header Manager -->
      </ConfigTestElement>
      <hashTree/>
${assertions}
      <!-- Summary Report -->
      <ResultCollector guiclass="SummaryReport" testclass="ResultCollector" testname="Summary Report">
        <boolProp name="ResultCollector.error_logging">false</boolProp>
        <objProp>
          <name>saveConfig</name>
          <value class="SampleSaveConfiguration">
            <time>true</time>
            <latency>true</latency>
            <timestamp>true</timestamp>
            <success>true</success>
            <label>true</label>
            <code>true</code>
            <message>true</message>
            <threadName>true</threadName>
            <dataType>true</dataType>
            <encoding>false</encoding>
            <assertions>true</assertions>
            <responseData>false</responseData>
          </value>
        </objProp>
        <stringProp name="filename">scalings-results.csv</stringProp>
      </ResultCollector>
      <hashTree/>
    </hashTree>
  </hashTree>
</jmeterTestPlan>`;
  }

  validate(config: SimulationConfig): LoadTestValidationResult {
    const warnings: string[] = [];
    const errors: string[] = [];

    const duration = config.simulation.duration;
    if (duration < 10) {
      warnings.push('Very short duration (< 10s) — JMeter may not produce meaningful results.');
    }

    const peakRps = this.estimatePeakRps(config);
    if (peakRps > 100000) {
      warnings.push(`Peak RPS of ~${Math.round(peakRps).toLocaleString()} will require many threads. Consider JMeter distributed testing.`);
    }

    warnings.push("JMeter uses a thread-based model which differs from the simulator's RPS model — the VU/thread mapping is approximate.");

    const pattern = config.producer.traffic.pattern;
    if (pattern === 'spike' || pattern === 'wave' || pattern === 'step' || pattern === 'custom' || pattern === 'grafana') {
      warnings.push('This traffic pattern requires the Ultimate Thread Group plugin (JMeter Plugins). Install via JMeter Plugins Manager.');
    }

    return { valid: errors.length === 0, warnings, errors };
  }

  private buildThreadGroups(pattern: string, params: unknown, duration: number, avgResponseSec: number, request: LoadTestRequestConfig): string {
    switch (pattern) {
      case 'steady': return this.steadyThreadGroup(params as SteadyParams, duration, avgResponseSec, request);
      case 'gradual': return this.gradualThreadGroup(params as GradualParams, duration, avgResponseSec, request);
      case 'spike': return this.spikeThreadGroup(params as SpikeParams, duration, avgResponseSec, request);
      case 'wave': return this.waveThreadGroup(params as WaveParams, duration, avgResponseSec, request);
      case 'step': return this.stepThreadGroup(params as StepParams, avgResponseSec, request);
      case 'custom':
      case 'grafana': return this.customThreadGroup(params as CustomParams, duration, avgResponseSec, request);
      default: return this.steadyThreadGroup({ rps: 100 }, duration, avgResponseSec, request);
    }
  }

  private wrapThreadGroup(name: string, threads: number, rampUp: number, duration: number, request: LoadTestRequestConfig): string {
    const method = this.escapeXml(request.method);
    const hasBody = request.body && ['POST', 'PUT', 'PATCH'].includes(request.method);
    const bodyXml = hasBody
      ? `\n          <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>\n          <elementProp name="HTTPsampler.Arguments" elementType="Arguments">\n            <collectionProp name="Arguments.arguments">\n              <elementProp name="" elementType="HTTPArgument">\n                <stringProp name="Argument.value">${this.escapeXml(this.replaceTemplateVars(request.body))}</stringProp>\n              </elementProp>\n            </collectionProp>\n          </elementProp>`
      : '';
    const headerXml = this.buildHeaderManager(request.headers);

    return `      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="${this.escapeXml(name)}">
        <intProp name="ThreadGroup.num_threads">${threads}</intProp>
        <intProp name="ThreadGroup.ramp_time">${rampUp}</intProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
        <stringProp name="ThreadGroup.duration">${duration}</stringProp>
        <boolProp name="ThreadGroup.scheduler">true</boolProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController">
          <intProp name="LoopController.loops">-1</intProp>
        </elementProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request">
          <stringProp name="HTTPSampler.path">\${TARGET_PATH}</stringProp>
          <stringProp name="HTTPSampler.method">${method}</stringProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>${bodyXml}
        </HTTPSamplerProxy>
        <hashTree/>
${headerXml}      </hashTree>`;
  }

  private wrapUltimateThreadGroup(name: string, schedule: { threads: number; initDelay: number; startupTime: number; holdTime: number; shutdownTime: number }[], request: LoadTestRequestConfig): string {
    const rows = schedule.map(row =>
      `            <collectionProp name="">
              <stringProp name="threads">${row.threads}</stringProp>
              <stringProp name="initDelay">${row.initDelay}</stringProp>
              <stringProp name="startupTime">${row.startupTime}</stringProp>
              <stringProp name="holdTime">${row.holdTime}</stringProp>
              <stringProp name="shutdownTime">${row.shutdownTime}</stringProp>
            </collectionProp>`
    ).join('\n');

    const method = this.escapeXml(request.method);
    const hasBody = request.body && ['POST', 'PUT', 'PATCH'].includes(request.method);
    const bodyXml = hasBody
      ? `\n          <boolProp name="HTTPSampler.postBodyRaw">true</boolProp>\n          <elementProp name="HTTPsampler.Arguments" elementType="Arguments">\n            <collectionProp name="Arguments.arguments">\n              <elementProp name="" elementType="HTTPArgument">\n                <stringProp name="Argument.value">${this.escapeXml(this.replaceTemplateVars(request.body))}</stringProp>\n              </elementProp>\n            </collectionProp>\n          </elementProp>`
      : '';
    const headerXml = this.buildHeaderManager(request.headers);

    return `      <!-- Requires JMeter Plugins: Ultimate Thread Group -->
      <kg.apc.jmeter.threads.UltimateThreadGroup guiclass="kg.apc.jmeter.threads.UltimateThreadGroupGui" testclass="kg.apc.jmeter.threads.UltimateThreadGroup" testname="${this.escapeXml(name)}">
        <collectionProp name="ultimatethreadgroupdata">
${rows}
        </collectionProp>
      </kg.apc.jmeter.threads.UltimateThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request">
          <stringProp name="HTTPSampler.path">\${TARGET_PATH}</stringProp>
          <stringProp name="HTTPSampler.method">${method}</stringProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>${bodyXml}
        </HTTPSamplerProxy>
        <hashTree/>
${headerXml}      </hashTree>`;
  }

  private rpsToThreads(rps: number, avgResponseSec: number): number {
    return Math.max(1, Math.ceil(rps * avgResponseSec));
  }

  private steadyThreadGroup(params: SteadyParams, duration: number, avgResponseSec: number, request: LoadTestRequestConfig): string {
    const threads = this.rpsToThreads(params.rps, avgResponseSec);
    return this.wrapThreadGroup('Steady Load', threads, Math.min(10, Math.floor(duration / 10)), duration, request);
  }

  private gradualThreadGroup(params: GradualParams, duration: number, avgResponseSec: number, request: LoadTestRequestConfig): string {
    const endThreads = this.rpsToThreads(Math.max(params.start_rps, params.end_rps), avgResponseSec);
    const startThreads = this.rpsToThreads(Math.min(params.start_rps, params.end_rps), avgResponseSec);
    return this.wrapThreadGroup('Gradual Ramp', endThreads, duration, duration, request);
  }

  private spikeThreadGroup(params: SpikeParams, duration: number, avgResponseSec: number, request: LoadTestRequestConfig): string {
    const baseThreads = this.rpsToThreads(params.base_rps, avgResponseSec);
    const spikeThreads = this.rpsToThreads(params.spike_rps, avgResponseSec);
    const spikeExtra = spikeThreads - baseThreads;

    return this.wrapUltimateThreadGroup('Spike Traffic', [
      { threads: baseThreads, initDelay: 0, startupTime: 5, holdTime: duration - 5, shutdownTime: 0 },
      { threads: Math.max(1, spikeExtra), initDelay: params.spike_start, startupTime: 1, holdTime: params.spike_duration, shutdownTime: 1 },
    ], request);
  }

  private waveThreadGroup(params: WaveParams, duration: number, avgResponseSec: number, request: LoadTestRequestConfig): string {
    // Approximate wave with Ultimate Thread Group steps
    const stepsPerPeriod = 8;
    const periods = Math.max(1, Math.floor(duration / params.period));
    const totalSteps = periods * stepsPerPeriod;
    const stepDuration = Math.max(1, Math.floor(duration / totalSteps));
    const schedule: { threads: number; initDelay: number; startupTime: number; holdTime: number; shutdownTime: number }[] = [];

    for (let i = 0; i < totalSteps; i++) {
      const angle = (2 * Math.PI * i) / stepsPerPeriod;
      const rps = Math.max(1, Math.round(params.base_rps + params.amplitude * Math.sin(angle)));
      const threads = this.rpsToThreads(rps, avgResponseSec);
      schedule.push({
        threads,
        initDelay: i * stepDuration,
        startupTime: 1,
        holdTime: stepDuration - 1,
        shutdownTime: 1,
      });
    }

    return this.wrapUltimateThreadGroup('Wave Traffic', schedule, request);
  }

  private stepThreadGroup(params: StepParams, avgResponseSec: number, request: LoadTestRequestConfig): string {
    const schedule: { threads: number; initDelay: number; startupTime: number; holdTime: number; shutdownTime: number }[] = [];
    let offset = 0;

    for (const step of params.steps) {
      const threads = this.rpsToThreads(step.rps, avgResponseSec);
      schedule.push({
        threads,
        initDelay: offset,
        startupTime: Math.min(5, Math.floor(step.duration / 10)),
        holdTime: step.duration - Math.min(5, Math.floor(step.duration / 10)),
        shutdownTime: 1,
      });
      offset += step.duration;
    }

    return this.wrapUltimateThreadGroup('Step Function', schedule, request);
  }

  private customThreadGroup(params: CustomParams, duration: number, avgResponseSec: number, request: LoadTestRequestConfig): string {
    const series = params.series;
    if (!series || series.length === 0) return this.steadyThreadGroup({ rps: 100 }, duration, avgResponseSec, request);

    const schedule: { threads: number; initDelay: number; startupTime: number; holdTime: number; shutdownTime: number }[] = [];

    for (let i = 0; i < series.length; i++) {
      const threads = this.rpsToThreads(series[i].rps, avgResponseSec);
      const startTime = Math.round(series[i].t);
      const endTime = i < series.length - 1 ? Math.round(series[i + 1].t) : duration;
      const holdTime = Math.max(1, endTime - startTime);

      schedule.push({
        threads,
        initDelay: startTime,
        startupTime: 1,
        holdTime,
        shutdownTime: 1,
      });
    }

    return this.wrapUltimateThreadGroup('Custom Traffic', schedule, request);
  }

  private buildAssertions(results?: SimulationResult): string {
    if (!results) return '';

    const lines: string[] = [];
    lines.push(`      <!-- Response Assertion -->`);
    lines.push(`      <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Status Code Check">`);
    lines.push(`        <collectionProp name="Asserion.test_strings">`);
    lines.push(`          <stringProp name="49586">200</stringProp>`);
    lines.push(`        </collectionProp>`);
    lines.push(`        <intProp name="Assertion.test_type">8</intProp>`);
    lines.push(`        <intProp name="Assertion.test_field">4</intProp>`);
    lines.push(`      </ResponseAssertion>`);
    lines.push(`      <hashTree/>`);

    return lines.join('\n');
  }

  private estimatePeakRps(config: SimulationConfig): number {
    const p = config.producer.traffic.params;
    switch (config.producer.traffic.pattern) {
      case 'steady': return (p as SteadyParams).rps;
      case 'gradual': return Math.max((p as GradualParams).start_rps, (p as GradualParams).end_rps);
      case 'spike': return (p as SpikeParams).spike_rps;
      case 'wave': return (p as WaveParams).base_rps + (p as WaveParams).amplitude;
      case 'step': return Math.max(...(p as StepParams).steps.map(s => s.rps), 0);
      case 'custom':
      case 'grafana': return Math.max(...((p as CustomParams).series || []).map(s => s.rps), 0);
      default: return 0;
    }
  }

  private replaceTemplateVars(str: string): string {
    return str
      .replace(/\$randInt/g, '${__Random(0,10000,)}')
      .replace(/\$randString/g, '${__RandomString(10,abcdefghijklmnopqrstuvwxyz0123456789,)}')
      .replace(/\$uuid/g, '${__UUID()}')
      .replace(/\$timestamp/g, '${__time(,)}')
      .replace(/\$randFloat/g, '${__groovy(Math.random(),)}')
      .replace(/\$randomEmail/g, 'user${__Random(0,99999,)}@loadtest.scalings.xyz');
  }

  private buildHeaderManager(headers: Record<string, string>): string {
    const entries = Object.entries(headers);
    if (entries.length === 0) return '';

    const headerElements = entries.map(([name, value]) =>
      `          <elementProp name="" elementType="Header">
            <stringProp name="Header.name">${this.escapeXml(name)}</stringProp>
            <stringProp name="Header.value">${this.escapeXml(this.replaceTemplateVars(value))}</stringProp>
          </elementProp>`
    ).join('\n');

    return `        <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="HTTP Header Manager">
          <collectionProp name="HeaderManager.headers">
${headerElements}
          </collectionProp>
        </HeaderManager>
        <hashTree/>
`;
  }

  private escapeXml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}
