// ============================================================================
// scalings.xyz — k6 Load Test Exporter
// ============================================================================

import {
  LoadTestExporter,
  LoadTestRequestConfig,
  LoadTestValidationResult,
  SimulationConfig,
  SimulationResult,
  SteadyParams,
  GradualParams,
  SpikeParams,
  WaveParams,
  StepParams,
  CustomParams,
  GrafanaParams,
} from '../../interfaces/types.js';

/** Map scalings template vars → k6 JS expressions */
const K6_VAR_MAP: Record<string, string> = {
  '$randInt': '${Math.floor(Math.random() * 10000)}',
  '$randString': '${randomString(10, \'abcdefghijklmnopqrstuvwxyz0123456789\')}',
  '$uuid': '${uuidv4()}',
  '$timestamp': '${Date.now()}',
  '$randFloat': '${Math.random().toFixed(6)}',
  '$randomEmail': '${`user${Math.floor(Math.random()*100000)}@loadtest.scalings.xyz`}',
};

function replaceVarsK6(input: string): string {
  let result = input;
  for (const [varName, replacement] of Object.entries(K6_VAR_MAP)) {
    result = result.split(varName).join(replacement);
  }
  return result;
}

function hasTemplateVars(input: string): boolean {
  return Object.keys(K6_VAR_MAP).some(v => input.includes(v));
}

export class K6Exporter implements LoadTestExporter {
  readonly id = 'k6' as const;
  readonly name = 'k6 (Grafana)';
  readonly extension = 'js';

  generate(config: SimulationConfig, targetUrl: string, avgResponseTime: number, request: LoadTestRequestConfig, results?: SimulationResult): string {
    const avgResponseSec = avgResponseTime / 1000;
    const duration = config.simulation.duration;
    const traffic = config.producer.traffic;
    const configJson = JSON.stringify(config);
    const shareUrl = `https://scalings.xyz/#config=${btoa(unescape(encodeURIComponent(configJson)))}`;

    const method = request.method;
    const hasBody = !!request.body && method !== 'GET' && method !== 'DELETE';
    const hasHeaders = Object.keys(request.headers).length > 0;
    const bodyHasVars = hasBody && hasTemplateVars(request.body);
    const headersHaveVars = hasHeaders && Object.values(request.headers).some(v => hasTemplateVars(v));
    const needsRandomString = (hasBody && request.body.includes('$randString'))
      || (hasHeaders && Object.values(request.headers).some(v => v.includes('$randString')));
    const needsUuid = (hasBody && request.body.includes('$uuid'))
      || (hasHeaders && Object.values(request.headers).some(v => v.includes('$uuid')));

    const lines: string[] = [];
    lines.push(`import http from 'k6/http';`);
    lines.push(`import { check, sleep } from 'k6';`);
    if (needsRandomString) {
      lines.push(`import { randomString } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';`);
    }
    if (needsUuid) {
      lines.push(`import { uuidv4 } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';`);
    }
    lines.push(``);
    lines.push(`// Generated by scalings.xyz — Autoscaling Simulator`);
    lines.push(`// Source config: ${config.name}`);
    lines.push(`// Simulation URL: ${shareUrl}`);
    lines.push(`//`);
    lines.push(`// Tunable: adjust AVG_RESPONSE_TIME to match your service's baseline`);
    lines.push(`const AVG_RESPONSE_TIME = ${avgResponseSec}; // seconds`);
    lines.push(`const TARGET_URL = '${targetUrl}';`);
    lines.push(``);

    const scenarios = this.buildScenarios(traffic.pattern, traffic.params, duration, avgResponseSec);
    const thresholds = this.buildThresholds(results);

    lines.push(`export const options = {`);
    lines.push(`  scenarios: {`);
    for (const scenario of scenarios) {
      lines.push(`    ${scenario.name}: {`);
      for (const [key, value] of Object.entries(scenario.config)) {
        lines.push(`      ${key}: ${this.formatValue(value)},`);
      }
      lines.push(`    },`);
    }
    lines.push(`  },`);
    if (thresholds.length > 0) {
      lines.push(`  thresholds: {`);
      for (const t of thresholds) {
        lines.push(`    '${t.metric}': [${t.conditions.map(c => `'${c}'`).join(', ')}],`);
      }
      lines.push(`  },`);
    }
    lines.push(`};`);
    lines.push(``);

    // Build default function
    lines.push(`export default function () {`);

    // Build params object if we have headers
    if (hasHeaders) {
      lines.push(`  const params = {`);
      lines.push(`    headers: {`);
      for (const [key, value] of Object.entries(request.headers)) {
        if (hasTemplateVars(value)) {
          lines.push(`      '${key}': \`${replaceVarsK6(value)}\`,`);
        } else {
          lines.push(`      '${key}': '${value}',`);
        }
      }
      lines.push(`    },`);
      lines.push(`  };`);
    }

    // Build body if needed
    if (hasBody) {
      if (bodyHasVars) {
        lines.push(`  const body = \`${replaceVarsK6(request.body)}\`;`);
      } else {
        lines.push(`  const body = ${this.escapeJsString(request.body)};`);
      }
    }

    // Build HTTP call
    const k6Method = method.toLowerCase();
    const paramsArg = hasHeaders ? 'params' : 'null';
    if (hasBody) {
      lines.push(`  const res = http.${k6Method}(TARGET_URL, body, ${paramsArg});`);
    } else if (hasHeaders) {
      if (method === 'GET' || method === 'DELETE') {
        lines.push(`  const res = http.${k6Method}(TARGET_URL, params);`);
      } else {
        lines.push(`  const res = http.${k6Method}(TARGET_URL, null, params);`);
      }
    } else {
      lines.push(`  const res = http.${k6Method}(TARGET_URL);`);
    }

    lines.push(`  check(res, {`);
    lines.push(`    'status is 200': (r) => r.status === 200,`);
    lines.push(`  });`);
    lines.push(`  sleep(AVG_RESPONSE_TIME);`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export function handleSummary(data) {`);
    lines.push(`  return {`);
    lines.push(`    'summary.json': JSON.stringify(data, null, 2),`);
    lines.push(`  };`);
    lines.push(`}`);

    return lines.join('\n');
  }

  validate(config: SimulationConfig): LoadTestValidationResult {
    const warnings: string[] = [];
    const errors: string[] = [];

    const duration = config.simulation.duration;
    if (duration < 10) {
      warnings.push('Very short duration (< 10s) — k6 may not produce meaningful results.');
    }

    const peakRps = this.estimatePeakRps(config);
    if (peakRps > 100000) {
      warnings.push(`Peak RPS of ~${Math.round(peakRps).toLocaleString()} will require many VUs. Consider distributed execution.`);
    }

    if (config.producer.traffic.pattern === 'grafana') {
      const params = config.producer.traffic.params as GrafanaParams;
      if (params.series.length < 2) {
        warnings.push('Grafana import has fewer than 2 data points — load shape may not be meaningful.');
      }
    }

    return { valid: errors.length === 0, warnings, errors };
  }

  private buildScenarios(
    pattern: string,
    params: unknown,
    duration: number,
    avgResponseSec: number,
  ): { name: string; config: Record<string, unknown> }[] {
    switch (pattern) {
      case 'steady':
        return this.steadyScenarios(params as SteadyParams, duration);
      case 'gradual':
        return this.gradualScenarios(params as GradualParams, duration);
      case 'spike':
        return this.spikeScenarios(params as SpikeParams, duration);
      case 'wave':
        return this.waveScenarios(params as WaveParams, duration);
      case 'step':
        return this.stepScenarios(params as StepParams);
      case 'custom':
      case 'grafana':
        return this.customScenarios(params as CustomParams, duration);
      default:
        return this.steadyScenarios({ rps: 100 }, duration);
    }
  }

  private steadyScenarios(params: SteadyParams, duration: number) {
    return [{
      name: 'steady_load',
      config: {
        executor: 'constant-arrival-rate',
        rate: params.rps,
        timeUnit: '1s',
        duration: `${duration}s`,
        preAllocatedVUs: Math.max(1, Math.ceil(params.rps * 0.1)),
        maxVUs: Math.max(10, Math.ceil(params.rps * 0.5)),
      },
    }];
  }

  private gradualScenarios(params: GradualParams, duration: number) {
    return [{
      name: 'gradual_ramp',
      config: {
        executor: 'ramping-arrival-rate',
        startRate: params.start_rps,
        timeUnit: '1s',
        preAllocatedVUs: Math.max(1, Math.ceil(params.start_rps * 0.1)),
        maxVUs: Math.max(10, Math.ceil(params.end_rps * 0.5)),
        stages: [
          { duration: `${duration}s`, target: params.end_rps },
        ],
      },
    }];
  }

  private spikeScenarios(params: SpikeParams, duration: number) {
    const stages: { duration: string; target: number }[] = [];
    const spikeEnd = params.spike_start + params.spike_duration;

    if (params.spike_start > 0) {
      stages.push({ duration: `${params.spike_start}s`, target: params.base_rps });
    }
    const rampUp = Math.max(1, Math.min(5, Math.floor(params.spike_duration * 0.1)));
    stages.push({ duration: `${rampUp}s`, target: params.spike_rps });
    const holdDuration = Math.max(1, params.spike_duration - rampUp);
    stages.push({ duration: `${holdDuration}s`, target: params.spike_rps });
    if (spikeEnd < duration) {
      stages.push({ duration: `${Math.min(5, duration - spikeEnd)}s`, target: params.base_rps });
      const remaining = duration - spikeEnd - Math.min(5, duration - spikeEnd);
      if (remaining > 0) {
        stages.push({ duration: `${remaining}s`, target: params.base_rps });
      }
    }

    return [{
      name: 'spike_traffic',
      config: {
        executor: 'ramping-arrival-rate',
        startRate: params.base_rps,
        timeUnit: '1s',
        preAllocatedVUs: Math.max(1, Math.ceil(params.base_rps * 0.1)),
        maxVUs: Math.max(10, Math.ceil(params.spike_rps * 0.5)),
        stages,
      },
    }];
  }

  private waveScenarios(params: WaveParams, duration: number) {
    const stepsPerPeriod = 12;
    const periods = Math.max(1, Math.floor(duration / params.period));
    const totalSteps = periods * stepsPerPeriod;
    const stepDuration = Math.max(1, Math.floor(duration / totalSteps));
    const stages: { duration: string; target: number }[] = [];

    for (let i = 0; i < totalSteps; i++) {
      const angle = (2 * Math.PI * i) / stepsPerPeriod;
      const rps = Math.max(1, Math.round(params.base_rps + params.amplitude * Math.sin(angle)));
      stages.push({ duration: `${stepDuration}s`, target: rps });
    }

    const peakRps = params.base_rps + params.amplitude;
    return [{
      name: 'wave_traffic',
      config: {
        executor: 'ramping-arrival-rate',
        startRate: params.base_rps,
        timeUnit: '1s',
        preAllocatedVUs: Math.max(1, Math.ceil(params.base_rps * 0.1)),
        maxVUs: Math.max(10, Math.ceil(peakRps * 0.5)),
        stages,
      },
    }];
  }

  private stepScenarios(params: StepParams) {
    const scenarios: { name: string; config: Record<string, unknown> }[] = [];
    let startTime = 0;

    for (let i = 0; i < params.steps.length; i++) {
      const step = params.steps[i];
      scenarios.push({
        name: `step_${i + 1}`,
        config: {
          executor: 'constant-arrival-rate',
          rate: step.rps,
          timeUnit: '1s',
          duration: `${step.duration}s`,
          preAllocatedVUs: Math.max(1, Math.ceil(step.rps * 0.1)),
          maxVUs: Math.max(10, Math.ceil(step.rps * 0.5)),
          startTime: `${startTime}s`,
        },
      });
      startTime += step.duration;
    }

    return scenarios;
  }

  private customScenarios(params: CustomParams, duration: number) {
    const series = params.series;
    if (!series || series.length === 0) {
      return this.steadyScenarios({ rps: 100 }, duration);
    }
    if (series.length === 1) {
      return this.steadyScenarios({ rps: series[0].rps }, duration);
    }

    const stages: { duration: string; target: number }[] = [];
    for (let i = 1; i < series.length; i++) {
      const segDuration = Math.max(1, Math.round(series[i].t - series[i - 1].t));
      stages.push({ duration: `${segDuration}s`, target: Math.max(1, Math.round(series[i].rps)) });
    }

    const lastT = series[series.length - 1].t;
    if (lastT < duration) {
      stages.push({ duration: `${Math.round(duration - lastT)}s`, target: Math.max(1, Math.round(series[series.length - 1].rps)) });
    }

    const peakRps = Math.max(...series.map(s => s.rps));
    return [{
      name: 'custom_traffic',
      config: {
        executor: 'ramping-arrival-rate',
        startRate: Math.max(1, Math.round(series[0].rps)),
        timeUnit: '1s',
        preAllocatedVUs: Math.max(1, Math.ceil(series[0].rps * 0.1)),
        maxVUs: Math.max(10, Math.ceil(peakRps * 0.5)),
        stages,
      },
    }];
  }

  private buildThresholds(results?: SimulationResult): { metric: string; conditions: string[] }[] {
    if (!results) return [];

    const thresholds: { metric: string; conditions: string[] }[] = [];
    const dropRate = results.summary.drop_rate_percent;

    const failThreshold = Math.max(1, Math.ceil(dropRate * 1.5));
    thresholds.push({
      metric: 'http_req_failed',
      conditions: [`rate<${(failThreshold / 100).toFixed(2)}`],
    });

    if (results.summary.avg_queue_wait_time_ms > 0) {
      const p95Ms = Math.ceil(results.summary.peak_queue_wait_time_ms * 0.95);
      thresholds.push({
        metric: 'http_req_duration',
        conditions: [`p(95)<${p95Ms}`],
      });
    }

    return thresholds;
  }

  private estimatePeakRps(config: SimulationConfig): number {
    const p = config.producer.traffic.params;
    switch (config.producer.traffic.pattern) {
      case 'steady': return (p as SteadyParams).rps;
      case 'gradual': return Math.max((p as GradualParams).start_rps, (p as GradualParams).end_rps);
      case 'spike': return (p as SpikeParams).spike_rps;
      case 'wave': return (p as WaveParams).base_rps + (p as WaveParams).amplitude;
      case 'step': return Math.max(...(p as StepParams).steps.map(s => s.rps), 0);
      case 'custom':
      case 'grafana': return Math.max(...((p as CustomParams).series || []).map(s => s.rps), 0);
      default: return 0;
    }
  }

  private formatValue(value: unknown): string {
    if (typeof value === 'string') return `'${value}'`;
    if (Array.isArray(value)) {
      if (value.length === 0) return '[]';
      const items = value.map(item => {
        if (typeof item === 'object' && item !== null) {
          const entries = Object.entries(item).map(([k, v]) => `${k}: ${this.formatValue(v)}`);
          return `{ ${entries.join(', ')} }`;
        }
        return this.formatValue(item);
      });
      return `[\n${items.map(i => `          ${i}`).join(',\n')},\n        ]`;
    }
    return String(value);
  }

  private escapeJsString(s: string): string {
    if (s.includes('\n') || s.includes("'")) {
      return '`' + s.replace(/`/g, '\\`') + '`';
    }
    return `'${s}'`;
  }
}
