// ============================================================================
// scalings.xyz — Locust Load Test Exporter
// ============================================================================

import {
  LoadTestExporter,
  LoadTestRequestConfig,
  LoadTestValidationResult,
  SimulationConfig,
  SimulationResult,
  SteadyParams,
  GradualParams,
  SpikeParams,
  WaveParams,
  StepParams,
  CustomParams,
  GrafanaParams,
} from '../../interfaces/types.js';

/** Map scalings template vars → Python expressions for Locust */
const LOCUST_VAR_MAP: Record<string, string> = {
  '$randInt': '{random.randint(0, 10000)}',
  '$randString': '{"".join(random.choices(string.ascii_lowercase + string.digits, k=10))}',
  '$uuid': '{str(uuid.uuid4())}',
  '$timestamp': '{int(time.time() * 1000)}',
  '$randFloat': '{random.random():.6f}',
  '$randomEmail': '{f"user{random.randint(0,99999)}@loadtest.scalings.xyz"}',
};

/** Which Python import module is needed for each template var */
const VAR_IMPORTS: Record<string, string[]> = {
  '$randInt': ['random'],
  '$randString': ['random', 'string'],
  '$uuid': ['uuid'],
  '$timestamp': ['time'],
  '$randFloat': ['random'],
  '$randomEmail': ['random'],
};

function replaceVarsLocust(input: string): string {
  let result = input;
  for (const [varName, replacement] of Object.entries(LOCUST_VAR_MAP)) {
    result = result.split(varName).join(replacement);
  }
  return result;
}

function hasTemplateVars(input: string): boolean {
  return Object.keys(LOCUST_VAR_MAP).some(v => input.includes(v));
}

/** Collect all Python imports needed for template vars present in the given strings */
function collectVarImports(...inputs: string[]): Set<string> {
  const imports = new Set<string>();
  for (const input of inputs) {
    for (const [varName, modules] of Object.entries(VAR_IMPORTS)) {
      if (input.includes(varName)) {
        for (const mod of modules) {
          imports.add(mod);
        }
      }
    }
  }
  return imports;
}

export class LocustExporter implements LoadTestExporter {
  readonly id = 'locust' as const;
  readonly name = 'Locust';
  readonly extension = 'py';

  generate(config: SimulationConfig, targetUrl: string, avgResponseTime: number, request: LoadTestRequestConfig, results?: SimulationResult): string {
    const avgResponseSec = avgResponseTime / 1000;
    const duration = config.simulation.duration;
    const traffic = config.producer.traffic;
    const configJson = JSON.stringify(config);
    const shareUrl = `https://scalings.xyz/#config=${btoa(unescape(encodeURIComponent(configJson)))}`;
    const needsShape = traffic.pattern !== 'steady';

    const method = request.method;
    const hasBody = !!request.body && method !== 'GET' && method !== 'DELETE';
    const hasHeaders = Object.keys(request.headers).length > 0;
    const bodyHasVars = hasBody && hasTemplateVars(request.body);
    const headersHaveVars = hasHeaders && Object.values(request.headers).some(v => hasTemplateVars(v));

    // Collect all strings that might contain template vars for import detection
    const allVarStrings: string[] = [];
    if (hasBody) allVarStrings.push(request.body);
    if (hasHeaders) allVarStrings.push(...Object.values(request.headers));
    const neededImports = collectVarImports(...allVarStrings);

    const lines: string[] = [];
    lines.push(`# Generated by scalings.xyz — Autoscaling Simulator`);
    lines.push(`# Source config: ${config.name}`);
    lines.push(`# Simulation URL: ${shareUrl}`);
    lines.push(`#`);
    if (needsShape) {
      lines.push(`# Run: locust -f scalings_loadtest.py --host ${targetUrl} --headless`);
    } else {
      const userCount = this.rpsToUsers(this.estimatePeakRps(config), avgResponseSec);
      lines.push(`# Run: locust -f scalings_loadtest.py --host ${targetUrl} --headless -u ${userCount} -r ${Math.max(1, Math.ceil(userCount / 10))} -t ${duration}s`);
    }
    lines.push(`#`);
    lines.push(`# Tunable: adjust AVG_RESPONSE_TIME to match your service's baseline`);
    lines.push(``);
    lines.push(`import math`);
    // Add Python imports needed for template vars
    for (const mod of ['random', 'string', 'uuid', 'time']) {
      if (neededImports.has(mod)) {
        lines.push(`import ${mod}`);
      }
    }
    lines.push(`from locust import HttpUser, task, between${needsShape ? ', LoadTestShape' : ''}`);
    lines.push(``);
    lines.push(`AVG_RESPONSE_TIME: float = ${avgResponseSec}  # seconds`);
    lines.push(``);
    lines.push(``);
    lines.push(`class ScalingsUser(HttpUser):`);
    lines.push(`    """Load test user generated from scalings.xyz simulation config."""`);
    lines.push(``);
    lines.push(`    wait_time = between(AVG_RESPONSE_TIME * 0.5, AVG_RESPONSE_TIME * 1.5)`);
    lines.push(``);
    lines.push(`    @task`);
    lines.push(`    def load_test(self) -> None:`);

    // Build headers dict if custom headers are provided
    if (hasHeaders) {
      lines.push(`        headers = {`);
      for (const [key, value] of Object.entries(request.headers)) {
        if (hasTemplateVars(value)) {
          lines.push(`            "${key}": f"${replaceVarsLocust(value)}",`);
        } else {
          lines.push(`            "${key}": "${value}",`);
        }
      }
      lines.push(`        }`);
    }

    // Build body if needed
    if (hasBody) {
      if (bodyHasVars) {
        // Use f-string for body with template vars
        const escapedBody = request.body.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
        lines.push(`        body = f"${replaceVarsLocust(escapedBody)}"`);
      } else {
        // Simple string constant
        if (request.body.includes('\n') || request.body.includes('"')) {
          lines.push(`        body = """${request.body}"""`);
        } else {
          lines.push(`        body = "${request.body}"`);
        }
      }
    }

    // Build HTTP call
    const pyMethod = method.toLowerCase();
    const callParts: string[] = [`"/"`];

    if (hasBody) {
      // Try to detect JSON body and use json= parameter
      const bodyStr = request.body.trim();
      if (bodyStr.startsWith('{') || bodyStr.startsWith('[')) {
        callParts.push(`json=__import__('json').loads(body)`);
      } else {
        callParts.push(`data=body`);
      }
    }

    if (hasHeaders) {
      callParts.push(`headers=headers`);
    }

    lines.push(`        self.client.${pyMethod}(${callParts.join(', ')})`);

    if (needsShape) {
      lines.push(``);
      lines.push(``);
      const shapeLines = this.buildShape(traffic.pattern, traffic.params, duration, avgResponseSec);
      for (const line of shapeLines) {
        lines.push(line);
      }
    }

    lines.push(``);

    return lines.join('\n');
  }

  validate(config: SimulationConfig): LoadTestValidationResult {
    const warnings: string[] = [];
    const errors: string[] = [];

    const duration = config.simulation.duration;
    if (duration < 10) {
      warnings.push('Very short duration (< 10s) — Locust may not produce meaningful results.');
    }

    const peakRps = this.estimatePeakRps(config);
    if (peakRps > 100000) {
      warnings.push(`Peak RPS of ~${Math.round(peakRps).toLocaleString()} will require many users. Consider distributed execution with multiple workers.`);
    }

    return { valid: errors.length === 0, warnings, errors };
  }

  private buildShape(pattern: string, params: unknown, duration: number, avgResponseSec: number): string[] {
    switch (pattern) {
      case 'gradual': return this.gradualShape(params as GradualParams, duration, avgResponseSec);
      case 'spike': return this.spikeShape(params as SpikeParams, duration, avgResponseSec);
      case 'wave': return this.waveShape(params as WaveParams, duration, avgResponseSec);
      case 'step': return this.stepShape(params as StepParams, avgResponseSec);
      case 'custom':
      case 'grafana': return this.customShape(params as CustomParams, duration, avgResponseSec);
      default: return [];
    }
  }

  private gradualShape(params: GradualParams, duration: number, avgResponseSec: number): string[] {
    const startUsers = this.rpsToUsers(params.start_rps, avgResponseSec);
    const endUsers = this.rpsToUsers(params.end_rps, avgResponseSec);
    const spawnRate = Math.max(1, Math.ceil(Math.abs(endUsers - startUsers) / duration * 10));

    return [
      `class ScalingsLoadShape(LoadTestShape):`,
      `    """Gradual ramp from ${params.start_rps} to ${params.end_rps} RPS over ${duration}s."""`,
      ``,
      `    duration: int = ${duration}`,
      `    start_users: int = ${startUsers}`,
      `    end_users: int = ${endUsers}`,
      ``,
      `    def tick(self) -> tuple[int, float, list[type[HttpUser]]] | None:`,
      `        run_time = self.get_run_time()`,
      `        if run_time > self.duration:`,
      `            return None`,
      ``,
      `        progress = run_time / self.duration`,
      `        users = int(self.start_users + (self.end_users - self.start_users) * progress)`,
      `        spawn_rate = max(1, ${spawnRate})`,
      `        return users, spawn_rate, [ScalingsUser]`,
    ];
  }

  private spikeShape(params: SpikeParams, duration: number, avgResponseSec: number): string[] {
    const baseUsers = this.rpsToUsers(params.base_rps, avgResponseSec);
    const spikeUsers = this.rpsToUsers(params.spike_rps, avgResponseSec);
    const spawnRate = Math.max(1, Math.ceil(spikeUsers / 10));

    return [
      `class ScalingsLoadShape(LoadTestShape):`,
      `    """Spike from ${params.base_rps} to ${params.spike_rps} RPS at t=${params.spike_start}s for ${params.spike_duration}s."""`,
      ``,
      `    duration: int = ${duration}`,
      `    base_users: int = ${baseUsers}`,
      `    spike_users: int = ${spikeUsers}`,
      `    spike_start: int = ${params.spike_start}`,
      `    spike_end: int = ${params.spike_start + params.spike_duration}`,
      ``,
      `    def tick(self) -> tuple[int, float, list[type[HttpUser]]] | None:`,
      `        run_time = self.get_run_time()`,
      `        if run_time > self.duration:`,
      `            return None`,
      ``,
      `        if self.spike_start <= run_time < self.spike_end:`,
      `            return self.spike_users, ${spawnRate}, [ScalingsUser]`,
      `        return self.base_users, ${spawnRate}, [ScalingsUser]`,
    ];
  }

  private waveShape(params: WaveParams, duration: number, avgResponseSec: number): string[] {
    const baseUsers = this.rpsToUsers(params.base_rps, avgResponseSec);
    const ampUsers = this.rpsToUsers(params.amplitude, avgResponseSec);
    const spawnRate = Math.max(1, Math.ceil((baseUsers + ampUsers) / 10));

    return [
      `class ScalingsLoadShape(LoadTestShape):`,
      `    """Sinusoidal traffic: base ${params.base_rps} RPS, amplitude ${params.amplitude}, period ${params.period}s."""`,
      ``,
      `    duration: int = ${duration}`,
      `    base_users: int = ${baseUsers}`,
      `    amplitude: int = ${ampUsers}`,
      `    period: int = ${params.period}`,
      ``,
      `    def tick(self) -> tuple[int, float, list[type[HttpUser]]] | None:`,
      `        run_time = self.get_run_time()`,
      `        if run_time > self.duration:`,
      `            return None`,
      ``,
      `        users = int(self.base_users + self.amplitude * math.sin(2 * math.pi * run_time / self.period))`,
      `        users = max(1, users)`,
      `        spawn_rate = max(1, ${spawnRate})`,
      `        return users, spawn_rate, [ScalingsUser]`,
    ];
  }

  private stepShape(params: StepParams, avgResponseSec: number): string[] {
    const totalDuration = params.steps.reduce((sum, s) => sum + s.duration, 0);
    const steps = params.steps.map(s => ({
      users: this.rpsToUsers(s.rps, avgResponseSec),
      duration: s.duration,
    }));
    const maxUsers = Math.max(...steps.map(s => s.users));
    const spawnRate = Math.max(1, Math.ceil(maxUsers / 10));

    const stepsList = steps.map(s => `(${s.users}, ${s.duration})`).join(', ');

    return [
      `class ScalingsLoadShape(LoadTestShape):`,
      `    """Step function traffic pattern."""`,
      ``,
      `    steps: list[tuple[int, int]] = [${stepsList}]  # (users, duration_seconds)`,
      ``,
      `    def tick(self) -> tuple[int, float, list[type[HttpUser]]] | None:`,
      `        run_time = self.get_run_time()`,
      `        elapsed = 0`,
      `        for users, duration in self.steps:`,
      `            if run_time < elapsed + duration:`,
      `                return users, max(1, ${spawnRate}), [ScalingsUser]`,
      `            elapsed += duration`,
      `        return None`,
    ];
  }

  private customShape(params: CustomParams, duration: number, avgResponseSec: number): string[] {
    const series = params.series;
    if (!series || series.length < 2) return [];

    const points = series.map(s => `(${Math.round(s.t)}, ${this.rpsToUsers(s.rps, avgResponseSec)})`).join(', ');
    const maxUsers = Math.max(...series.map(s => this.rpsToUsers(s.rps, avgResponseSec)));
    const spawnRate = Math.max(1, Math.ceil(maxUsers / 10));

    return [
      `class ScalingsLoadShape(LoadTestShape):`,
      `    """Custom traffic shape with linear interpolation between points."""`,
      ``,
      `    duration: int = ${duration}`,
      `    points: list[tuple[int, int]] = [${points}]  # (time_seconds, users)`,
      ``,
      `    def tick(self) -> tuple[int, float, list[type[HttpUser]]] | None:`,
      `        run_time = self.get_run_time()`,
      `        if run_time > self.duration:`,
      `            return None`,
      ``,
      `        # Interpolate between points`,
      `        for i in range(len(self.points) - 1):`,
      `            t0, u0 = self.points[i]`,
      `            t1, u1 = self.points[i + 1]`,
      `            if t0 <= run_time <= t1:`,
      `                progress = (run_time - t0) / max(1, t1 - t0)`,
      `                users = int(u0 + (u1 - u0) * progress)`,
      `                return max(1, users), max(1, ${spawnRate}), [ScalingsUser]`,
      ``,
      `        # Hold last value`,
      `        return max(1, self.points[-1][1]), max(1, ${spawnRate}), [ScalingsUser]`,
    ];
  }

  private rpsToUsers(rps: number, avgResponseSec: number): number {
    return Math.max(1, Math.ceil(rps * avgResponseSec));
  }

  private estimatePeakRps(config: SimulationConfig): number {
    const p = config.producer.traffic.params;
    switch (config.producer.traffic.pattern) {
      case 'steady': return (p as SteadyParams).rps;
      case 'gradual': return Math.max((p as GradualParams).start_rps, (p as GradualParams).end_rps);
      case 'spike': return (p as SpikeParams).spike_rps;
      case 'wave': return (p as WaveParams).base_rps + (p as WaveParams).amplitude;
      case 'step': return Math.max(...(p as StepParams).steps.map(s => s.rps), 0);
      case 'custom':
      case 'grafana': return Math.max(...((p as CustomParams).series || []).map(s => s.rps), 0);
      default: return 0;
    }
  }
}
